networks:
  iCallOn:

services:
  postgres:
    image: postgres:12.20-alpine
    volumes:
      - "postgres_data:/var/lib/postgresql/data"
    environment:
      - POSTGRES_USER=nelwhix
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=iCallOn-db
    ports:
      - "5432:5432"

volumes:
  postgres_data:
    driver: local